version: "3.7"
services:
  web-server:
    build:
      dockerfile: concept.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"
volumes:
  mysql-data:
